/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.Ventanas_Secundarias;

import controladores.UsuarioBean;
import modelos.Usuario;
import vistas.Fondo;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaVentas extends Fondo {
JFrame frame = new JFrame();
    /**
     * Creates new form TablaUsuarios
     */
    public VentanaVentas() {
        initComponents();
    }
    public VentanaVentas(JFrame jframe) {
        initComponents();
        frame = jframe;
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 375, 92));
    }// </editor-fold>//GEN-END:initComponents

public void cargarUsuarios() {
        UsuarioBean op = new UsuarioBean();
        List listUsuarios = op.listUsuario();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Usuario");
        modelo.addColumn("Administrador");
        Iterator it = listUsuarios.iterator();
        while (it.hasNext()) {
            Usuario u = (Usuario) it.next();
            Object[] fila = new Object[3];
            fila[0] = u.getIdUsuario();
            fila[1] = u.getUsuario();
            fila[2] = u.getAdmin();
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
