/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package entremarcas_app.VentanasPrincipales;

import entremarcas_app.Ventanas_Secundarias.VentanaCrearUsuario;
import entidades.Talla;
import entidades.Usuario;
import entremarcas_app.Fondo;
import hibernate.utils.OperacionesCRUD;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Login extends Fondo {

    JFrame frame = new JFrame();

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();

    }

    public Login(JFrame jframe) {

        initComponents();
        frame = jframe;
        btnAceptar.setEnabled(false);

    }

    public void habilitarBoton() {
        if (!txtUser.getText().isEmpty()) {
            btnAceptar.setEnabled(true);
        } else {
            btnAceptar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPas = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img3.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 30, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img1.png"))); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(30, 30));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 30, 30));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/63474_lock_locked_log in_login_padlock_icon (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 70));

        txtUser.setPreferredSize(new java.awt.Dimension(64, 25));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 30));

        txtPas.setPreferredSize(new java.awt.Dimension(64, 25));
        add(txtPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        String user = txtUser.getText();
        String pas = txtPas.getText();
        OperacionesCRUD op = new OperacionesCRUD();
        List<Usuario> users = (List<Usuario>) op.listUsuario();
        for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUsuario().equals(user) && users.get(i).getPassword().equals(pas)) {
                if (users.get(i).getAdmin()) {
                    this.setVisible(false);
                    frame.remove(this);
                    VentanaAdmin admin = new VentanaAdmin(frame);
                    frame.getContentPane().add(admin);
                    admin.setVisible(true);
                    admin.setBounds(0, 0, 650, 400);
                    frame.setSize(650, 400);
                    JOptionPane.showMessageDialog(null, "Bienvenido "+users.get(i).getUsuario());
                } else {
                    this.setVisible(false);
                    frame.remove(this);
                    VentanaCrearUsuario usuario = new VentanaCrearUsuario(frame);
                    frame.getContentPane().add(usuario);
                    frame.setSize(603, 402);
                    usuario.setVisible(true);
                    usuario.setSize(603, 402);
                    JOptionPane.showMessageDialog(null, "Bienvenido "+users.get(i).getUsuario());
                }
            }
        }
        /*if (txtUser.getText().equalsIgnoreCase("admin")) {
            Conector conecta = new Conector();
            Connection con = conecta.getConexion();
            JOptionPane.showMessageDialog(null, "Conexión establecida con éxito");
            this.setVisible(false);
            frame.remove(this);
            ProductoPanel i = new ProductoPanel(frame);
            frame.getContentPane().add(i);
            i.setVisible(true);
            i.setBounds(0, 0, 650, 400);
            frame.setSize(650, 400);
        } else {
            this.setVisible(false);
            frame.remove(this);
            VentanaUsuario i = new VentanaUsuario(frame);
            frame.getContentPane().add(i);
            frame.setSize(603, 402);
            i.setVisible(true);
            i.setSize(603, 402);
        }*/
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_txtUserKeyReleased

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPas;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
