package entidades;
// Generated 14 nov. 2022 19:37:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Talla generated by hbm2java
 */
public class Talla  implements java.io.Serializable {


     private int idTalla;
     private String nombreTalla;
     private Set productos = new HashSet(0);

    public Talla() {
    }

	
    public Talla(int idTalla, String nombreTalla) {
        this.idTalla = idTalla;
        this.nombreTalla = nombreTalla;
    }
    public Talla(int idTalla, String nombreTalla, Set productos) {
       this.idTalla = idTalla;
       this.nombreTalla = nombreTalla;
       this.productos = productos;
    }
   
    public int getIdTalla() {
        return this.idTalla;
    }
    
    public void setIdTalla(int idTalla) {
        this.idTalla = idTalla;
    }
    public String getNombreTalla() {
        return this.nombreTalla;
    }
    
    public void setNombreTalla(String nombreTalla) {
        this.nombreTalla = nombreTalla;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


