package entidades;
// Generated 14 nov. 2022 19:37:49 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int codVenta;
     private Cliente cliente;
     private Producto producto;
     private Date fecha;
     private Boolean online;
     private String ciudad;
     private Integer costoDeEnvio;
     private Boolean estado;

    public Venta() {
    }

	
    public Venta(int codVenta, Producto producto) {
        this.codVenta = codVenta;
        this.producto = producto;
    }
    public Venta(int codVenta, Cliente cliente, Producto producto, Date fecha, Boolean online, String ciudad, Integer costoDeEnvio, Boolean estado) {
       this.codVenta = codVenta;
       this.cliente = cliente;
       this.producto = producto;
       this.fecha = fecha;
       this.online = online;
       this.ciudad = ciudad;
       this.costoDeEnvio = costoDeEnvio;
       this.estado = estado;
    }
   
    public int getCodVenta() {
        return this.codVenta;
    }
    
    public void setCodVenta(int codVenta) {
        this.codVenta = codVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getOnline() {
        return this.online;
    }
    
    public void setOnline(Boolean online) {
        this.online = online;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Integer getCostoDeEnvio() {
        return this.costoDeEnvio;
    }
    
    public void setCostoDeEnvio(Integer costoDeEnvio) {
        this.costoDeEnvio = costoDeEnvio;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


