package vistas.VentanasPrincipales;

import controladores.MarcaBean;
import controladores.ProductoBean;
import controladores.TallaBean;
import java.text.DecimalFormat;
import java.util.ArrayList;
import modelos.Producto;
import vistas.Fondo;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Marca;
import modelos.Talla;
import vistas.Ventanas_Secundarias.VentanaVender;

/**
 * Clase VentanaVendedor extiende de la Clase Fondo, si el usuario ingresado en el login
 * no es admin, se iniciara esta ventana, presenta una lista de productos
 * disponibles, los cuales podra agregar al carrito y abrir la ventana carrito
 * si este no se encuentra vacio
 *
 * @author Carlos Halberth Almanza Lopez
 */
public class VentanaVendedor extends Fondo {

    JFrame frame = new JFrame();
    ArrayList<Integer> carrito = new ArrayList();

    /**
     * Creates new form Venta
     */
    public VentanaVendedor() {
        initComponents();
    }

    /**
     * Creates new form VentanaVendedor
     *
     * @param jframe
     */
    public VentanaVendedor(JFrame jframe) {

        initComponents();
        frame = jframe;
        cargarProductos();
        btnAgregarProducto.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIdProducto = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 178));

        txtIdProducto.setText("Ingrese el codigo");
        txtIdProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdProductoFocusGained(evt);
            }
        });
        txtIdProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProductoKeyTyped(evt);
            }
        });
        add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        btnAgregarProducto.setText("Agregar al Carrito");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Lista de Productos");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setMinimumSize(new java.awt.Dimension(623, 36));
        jLabel13.setPreferredSize(new java.awt.Dimension(643, 70));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 300, 50));

        jButton1.setText("Ir Al Carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        /**
         * Evento para buscar un Producto y mostrarlo en la tabla, si esta
         * disponible.
         */
        if (!txtIdProducto.getText().equalsIgnoreCase("Ingrese el codigo")) {
            if (!txtIdProducto.getText().isEmpty() && txtIdProducto.getText() != null) {
                DecimalFormat df = new DecimalFormat("#");
                ProductoBean op = new ProductoBean();
                TallaBean tb = new TallaBean();
                MarcaBean mb = new MarcaBean();
                Producto p = op.obtenerProducto(Integer.parseInt(txtIdProducto.getText()));
                if (p != null && p.getDisponible()) {
                    Talla t = p.getTalla();
                    Marca m = p.getMarca();
                    int id = t.getIdTalla();
                    int id_marca = m.getIdMarca();
                    DefaultTableModel modelo = new DefaultTableModel();
                    Talla talla = tb.obtenerTalla(id);
                    Marca marca = mb.obtenerMarca(id_marca);
                    modelo.addColumn("Codigo");
                    modelo.addColumn("Nombre");
                    modelo.addColumn("Talla");
                    modelo.addColumn("Marca");
                    modelo.addColumn("Precio");
                    if (p.getDisponible()) {
                        Object[] fila = new Object[5];
                        fila[0] = p.getCodigo();
                        fila[1] = p.getNombre().toUpperCase();
                        fila[2] = talla.getNombreTalla().toUpperCase();
                        fila[3] = marca.getNombreMarca().toUpperCase();
                        fila[4] = df.format(p.getPrecioDeVenta());
                        modelo.addRow(fila);
                        jTable1.setModel(modelo);
                    }
                } else {
                    cargarProductos();
                    JOptionPane.showMessageDialog(null, "El Codigo no existe", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                cargarProductos();
            }
            txtIdProducto.setText("Ingrese el codigo");
        } else {
            cargarProductos();
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdProductoFocusGained
        //Evento para establecer el textfield a vacio
        txtIdProducto.setText("");

    }//GEN-LAST:event_txtIdProductoFocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Evento que activa el boton agregar al dar click en un elemento de la tabla
        btnAgregarProducto.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtIdProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProductoKeyTyped
        //Evento para restringir la escritura de solo numeros
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdProductoKeyTyped

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        //Evento para agregar un producto de la lista al carrito
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        String dato = String.valueOf(dtm.getValueAt(jTable1.getSelectedRow(), 0));
        int id = Integer.parseInt(dato);
        if (!carrito.contains(id)) {
            carrito.add(id);
            JOptionPane.showMessageDialog(null, "Agregado al carrito Correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "El producto ya esta en el carrito", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Evento para ir a la ventana del carrito si este no esta vacio
        if (!carrito.isEmpty() && carrito != null) {
            this.setVisible(false);
            frame.remove(this);
            VentanaVender productos = new VentanaVender(frame, carrito);
            frame.getContentPane().add(productos);
            frame.setSize(603, 435);
            productos.setVisible(true);
            productos.setSize(603, 435);
        } else {
            JOptionPane.showMessageDialog(null, "El carrito esta vacio!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Evento para volver a la ventana del Login
        this.setVisible(false);
        frame.remove(this);
        Login i = new Login(frame);
        frame.getContentPane().add(i);
        frame.setSize(300, 300);
        i.setVisible(true);
        i.setSize(300, 300);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Metodo para cargar la tabla con los productos, solo se cargaran los
     * productos disponibles
     */
    public void cargarProductos() {
        DecimalFormat df = new DecimalFormat("#");
        ProductoBean op = new ProductoBean();
        TallaBean tb = new TallaBean();
        MarcaBean mb = new MarcaBean();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Talla");
        modelo.addColumn("Marca");
        modelo.addColumn("Precio");
        List listaProductos = op.listProducto();
        if (listaProductos != null) {
            for (Iterator iterator = listaProductos.iterator(); iterator.hasNext();) {
                Producto p = (Producto) iterator.next();
                Talla t = p.getTalla();
                Marca m = p.getMarca();
                int id = t.getIdTalla();
                int id_marca = m.getIdMarca();
                Talla talla = tb.obtenerTalla(id);
                Marca marca = mb.obtenerMarca(id_marca);
                if (p.getDisponible()) {
                    Object[] fila = new Object[5];
                    fila[0] = p.getCodigo();
                    fila[1] = p.getNombre().toUpperCase();
                    fila[2] = talla.getNombreTalla().toUpperCase();
                    fila[3] = marca.getNombreMarca().toUpperCase();
                    fila[4] = df.format(p.getPrecioDeVenta());
                    modelo.addRow(fila);
                }
            }
        }
        jTable1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIdProducto;
    // End of variables declaration//GEN-END:variables

}
