package modelos;
// Generated 14 nov. 2022 19:37:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codCliente;
     private String nombre;
     private String apellidos;
     private Integer telefono;
     private String ciudad;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String ciudad) {

        this.nombre = nombre;
        this.ciudad = ciudad;
    }
    public Cliente(String nombre, String apellidos, Integer telefono, String ciudad, Set ventas) {
      
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.ciudad = ciudad;
       this.ventas = ventas;
    }
   
    public int getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(int codCliente) {
        this.codCliente = codCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


