package modelos;
// Generated 19-nov-2022 22:23:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer idMarca;
     private String nombreMarca;
     private Boolean disponible=true;
     private Set productos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public Marca(String nombreMarca, Boolean disponible, Set productos) {
       this.nombreMarca = nombreMarca;
       this.disponible = disponible;
       this.productos = productos;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }

    public Boolean getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(Boolean disponible) {
        this.disponible = disponible;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


