package modelos;
// Generated 14 nov. 2022 19:37:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int idMarca;
     private String nombreMarca;
     private String pais;
     private Set productos = new HashSet(0);

    public Marca() {
    }

	
    public Marca( String nombreMarca) {
        
        this.nombreMarca = nombreMarca;
    }
    public Marca( String nombreMarca, String pais, Set productos) {
       
       this.nombreMarca = nombreMarca;
       this.pais = pais;
       this.productos = productos;
    }
   
    public int getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(int idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


